In [1]:
import numpy as np
import pandas as pd

#### Groupby allows you to group data together.
##### it's often refered to as Split-Apply-Combine

In [2]:
df = pd.read_csv('Universities.csv')

In [3]:
df

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada
...,...,...,...,...,...
202,"Private for-profit, 2-year",Carrington College-Las Vegas,2012,120,Nevada
203,"Public, 4-year or above",Western Nevada College,2012,495,Nevada
204,"Private for-profit, 2-year",Nevada Career Institute,2012,101,Nevada
205,"Private not-for-profit, 2-year",Expertise Cosmetology Institute,2012,129,Nevada
206,"Public, 2-year",Truckee Meadows Community College,2012,1170,Nevada

#### .head() grabs the first 5 rows of a dataframe

In [4]:
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

#### 1. group by a categorical column

In [10]:
df.groupby('Year')

#### 2. Use an aggregate function

In [13]:
df.groupby('Year').sum().sort_index(ascending=False)

,Sector,University,Completions,Geography
Year,,,,
2016,"Private for-profit, 2-yearPrivate for-profit, ...",Pima Medical Institute-Las VegasHealthcare Pre...,26224,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2015,"Private for-profit, 2-yearPrivate not-for-prof...",Pima Medical Institute-Las VegasRoseman Univer...,26279,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2014,"Private not-for-profit, 4-year or abovePrivate...",Roseman University of Health SciencesExpertise...,24730,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2013,"Private for-profit, 2-yearPrivate for-profit, ...",Aviation Institute of Maintenance-Las VegasDeV...,21046,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2012,"Private for-profit, less-than 2-yearPrivate fo...",Academy of Hair Design-Las VegasCareer College...,20333,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...

#### You can group by multiple columns and return multiteared indexes

In [14]:
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

In [15]:
df.groupby(['Year', 'Sector']).sum()

                                                                                     University  \
Year Sector
2012 Private for-profit, 2-year               Career College of Northern NevadaPaul Mitchell...
     Private for-profit, 4-year or above      Sanford-Brown College-Las VegasITT Technical I...
     Private for-profit, less-than 2-year     Academy of Hair Design-Las VegasMilan Institut...
     Private not-for-profit, 2-year           Everest College-HendersonExpertise Cosmetology...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesTouro Uni...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  University of Nevada-RenoCollege of Southern N...
2013 Private for-profit, 2-year               Aviation Institute of Maintenance-Las VegasCar...
     Private for-profit, 4-year or above      DeVry University-NevadaITT Technical Institute...
     Private for-profit, less-than 2-year     Academy of Hair Design-Las VegasMilan Institut...
     Private not-for-profit, 2-year           Expertise Cosmetology InstituteEverest College...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesTouro Uni...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  University of Nevada-RenoUniversity of Nevada-...
2014 Private for-profit, 2-year               Nevada Career InstituteEuphoria Institute of B...
     Private for-profit, 4-year or above      Sanford-Brown College-Las VegasThe Art Institu...
     Private for-profit, less-than 2-year     Healthcare Preparatory InstituteMilan Institut...
     Private not-for-profit, 2-year           Expertise Cosmetology InstituteEverest College...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesSierra Ne...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  College of Southern NevadaWestern Nevada Colle...
2015 Private for-profit, 2-year               Pima Medical Institute-Las VegasBrightwood Col...
     Private for-profit, 4-year or above      ITT Technical Institute-Las VegasUniversity of...
     Private for-profit, less-than 2-year     Milan Institute-SparksHealthcare Preparatory I...
     Private not-for-profit, 2-year           Everest College-HendersonExpertise Cosmetology...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesSierra Ne...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  University of Nevada-Las VegasGreat Basin Coll...
2016 Private for-profit, 2-year               Pima Medical Institute-Las VegasNorthwest Care...
     Private for-profit, 4-year or above      University of Phoenix-NevadaChamberlain Colleg...
     Private for-profit, less-than 2-year     Healthcare Preparatory InstituteMilan Institut...
     Private not-for-profit, 2-year           Everest College-HendersonExpertise Cosmetology...
     Private not-for-profit, 4-year or above  Sierra Nevada CollegeWongu University of Orien...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  Western Nevada CollegeGreat Basin CollegeNevad...

                                              Completions  \
Year Sector
2012 Private for-profit, 2-year                      3072
     Private for-profit, 4-year or above              632
     Private for-profit, less-than 2-year            1327
     Private not-for-profit, 2-year                   665
     Private not-for-profit, 4-year or above         1059
     Public, 2-year                                  1170
     Public, 4-year or above                        12408
2013 Private for-profit, 2-year                      3053
     Private for-profit, 4-year or above              775
     Private for-profit, less-than 2-year            1281
     Private not-for-profit, 2-year                   471
     Private not-for-profit, 4-year or above         1016
     Public, 2-year                                  1633
     Public, 4-year or above                        12817
2014 Private for-profit, 2-year                      2957
     Private for-profit, 4-year or above             1506
     Private for-profit, less-than 2-year            1328
     Private not-for-profit, 2-year                   449
     Private not-for-profit, 4-year or above         1042
     Public, 2-year                                  2286
     Public, 4-year or above                        15162
2015 Private for-profit, 2-year                      3280
     Private for-profit, 4-year or above             1306
     Private for-profit, less-than 2-year            1629
     Private not-for-profit, 2-year                   425
     Private not-for-profit, 4-year or above         1228
     Public, 2-year                                  2355
     Public, 4-year or above                        16056
2016 Private for-profit, 2-year                      3286
     Private for-profit, 4-year or above              748
     Private for-profit, less-than 2-year            1552
     Private not-for-profit, 2-year                   322
     Private not-for-profit, 4-year or above         1208
     Public, 2-year                                  2431
     Public, 4-year or above                        16677

                                                                                      Geography
Year Sector
2012 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                               NevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year            NevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2013 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                         NevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year            NevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2014 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                   NevadaNevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year      NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2015 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above       NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year      NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2016 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                   NevadaNevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year      NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                           NevadaNevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada

#### Combine groupby

In [17]:
df.groupby('Year').describe().transpose()

Year                      2012         2013         2014         2015  \
Completions count    38.000000    40.000000    42.000000    44.000000
            mean    535.078947   526.150000   588.809524   597.250000
            std    1036.433239  1040.474782  1150.355857  1183.371791
            min      13.000000     0.000000     0.000000     0.000000
            25%     114.250000    98.500000   104.500000    87.750000
            50%     229.500000   189.000000   203.500000   191.000000
            75%     420.500000   413.000000   371.750000   405.750000
            max    5388.000000  5278.000000  5093.000000  5335.000000

Year                      2016
Completions count    43.000000
            mean    609.860465
            std    1235.952796
            min       0.000000
            25%      90.000000
            50%     208.000000
            75%     414.000000
            max    5367.000000